image:
  repository: inbucket/inbucket
  tag: 3.0.4
  pullPolicy: IfNotPresent

service:
  port:
    http: 9000
    smtp: 25
    pop3: 1100

extraEnv:
  INBUCKET_SMTP_ACCEPTDOMAINS: "morjoff.com"

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-inbucket-redirect@kubernetescrd

  hosts:
    - host: inbucket.morjoff.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: inbucket.local
            servicePort: 80
  tls:
    - secretName: inbucket.morjoff.com
      hosts:
        - inbucket.morjoff.com
