apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "inbucket.name" . }}-redirect
  labels:
    {{- include "inbucket.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true