apiVersion: v1
kind: Service
metadata:
  name: {{ include "inbucket.fullname" . }}-http
  labels:
    {{- include "inbucket.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: proxy
      port: 4180
      protocol: TCP
      targetPort: proxy
  selector:
    app.kubernetes.io/name: {{ include "inbucket.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
