name: deploy-prod
on:
  workflow_dispatch:
jobs:
  deploy-to-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.6.3

      - name: Set k8s context
        uses: Azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Set up Tailscale VPN
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
          args: --login-server=https://morjoffhs.duckdns.org

      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade --install \
            inbucket helm --values values.yaml
