name: deploy-prod
on:
  workflow_dispatch:
jobs:
  deploy-to-k8s:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.6.3

      - name: Set k8s context
        uses: Azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Set up Tailscale VPN
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
          args: --login-server=https://headscale.morjoff.com

      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade --install inbucket . --values values.yaml \
          --set "authenticatedEmails[0]=${{ secrets.OAUTH2_PROXY_AUTHENTICATED_EMAIL }}" \
          --set "oauth2Proxy.clientId=${{ secrets.OAUTH2_PROXY_CLIENT_ID }}" \
          --set "oauth2Proxy.clientSecret=${{ secrets.OAUTH2_PROXY_CLIENT_SECRET }}" \
          --set "oauth2Proxy.cookieSecret=${{ secrets.OAUTH2_PROXY_COOKIE_SECRET }}" \
